api_platform:
    title: API Serre Maraîchage
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_enabled: true
        pagination_items_per_page: 5
        pagination_maximum_items_per_page: 100
        pagination_client_enabled: true
        pagination_client_items_per_page: true

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header