security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/auth_token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

    access_control:
        - { path: ^/api/$, roles: PUBLIC_ACCESS }                     # Permet d'accéder à l'interface utilisateur de Swagger
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }                  # Permet d'accéder à la documentation de l'interface utilisateur Swagger
        - { path: ^/api/auth_token, roles: PUBLIC_ACCESS }            # Autorise tout le monde à se connecter
        - { path: ^/api/mesures$, roles: PUBLIC_ACCESS }              # Autorise les requêtes POST sur /api/mesures pour l'Arduino
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }              # Toutes les autres routes /api/* nécessitent un JWT valide

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
